# Generated by Django 2.0.7 on 2018-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarsiTed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('event', models.CharField(max_length=500, null=True)),
                ('low', models.CharField(max_length=500, null=True)),
                ('medium', models.CharField(max_length=500, null=True)),
                ('high', models.CharField(max_length=500, null=True)),
                ('fasub', models.CharField(max_length=500, null=True)),
                ('engsub', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
